### ISSUE TITLE
Multiple versions

### ISSUE THREAD

**Issue by jdwh** [joepitt91/SignClickOnceApp#1]
Set up a sandbox. Did initial publish.  SignClickOnceApp worked great.   Published a second time creating version 1.0.0.1.  Then it errored out on line 192 with "Internal error, please try again. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.".  My guess is add a foreach right after "Write-Verbose "Signing '$TargetPath\$ProjectName.exe.deploy' (SHA256)"

**Comment by joepitt91** [comment]
Thanks for the report, I will have a look at this in the new year. Instead of a `foreach` I will look to only sign the latest version, so that each version retains its original sign date.

# Workaround
1. Publish your app
2. Run SignClickonceApp
3. Move signed app to final publish location (not copy)

**Comment by joepitt91** [comment]
Fixed in 850a21fe33a3d894958a16bfe545e44a06581976, released as v2.1.

Hope that fixes your issue @jdwh
